name: Semgrep

on:
  pull_request: {}
  push:
    branches: ["main", "master"]

jobs:
  semgrep:
    name: Scan
    runs-on: Ubuntu-latest

    steps:
     - Uses: actions/checkout@v3

     - uses: returntocorp/semgrep-action@v1
       with:
         config: >-
           p/security-audit
           p/owasp-top-ten
